# blender_manifest.toml
# Manifest file for the BL Easy Crop Extension

# Blender Extension Manifest
schema_version = "1.0.0"
id = "BL_EasyCrop"
version = "2.0.1"

name = "BL Easy Crop"
tagline = "Use handles for easy cropping in the Blender VSE Preview window"
type = "add-on"

# Author and maintainer info
author = "usrname0"
maintainer = "usrname0"

# Links
website = "https://github.com/usrname0/BL_EasyCrop"

# Tags for discoverability
tags = ["Sequencer", "User Interface"]

# Requirements
blender_version_min = "4.4.0"

# License - must be GPL compatible
license = ["SPDX:GPL-3.0-or-later"]

# Description - must be clear about all functionality
description = """A simplified cropping interface for the built-in crop in Blender's Video Sequence Editor (VSE).

Features:
• Crop looks and behaves a bit more like the other transforms (rotate, resize, move, transform)
• Click and drag handles to crop in the VSE Preview window
• Select the crop tool via toolbar, menu or shortcut (default "C")
• Respects user's custom-keybinds
• Works with all strip types that support cropping
"""

# Copyright notices
copyright = [
    "2025 usrname0",
    "2007 Original VSE Transform Tools by kgeogeo, DoubleZ, doakey3, NathanLovato",
]

# Build configuration
[build]
paths_exclude_pattern = [
    "__pycache__/",
    "*.pyc",
    ".*",
    "/.git/",
    "/.gitignore",
    "/.github/",
	"/icons/*.png",
	"/icons/*.svg",
    "/docs/",
    "/tests/",
    "/*.md",
    "/*.zip",
    "/zips/",
    "/.vscode/",
    "/examples/",
]